=== pcantrell/macker/macker/test/macker.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!ELEMENT macker (ruleset)+>

<!ELEMENT ruleset (pattern|foreach|access-rule)*>
<!ATTLIST ruleset name  CDATA #IMPLIED> 

<!ELEMENT foreach (pattern|foreach|access-rule)*>
<!ATTLIST foreach var   CDATA #REQUIRED> 
<!ATTLIST foreach regex CDATA #REQUIRED> 

<!ELEMENT pattern ((include|exclude)*)>
<!ATTLIST pattern name  CDATA #REQUIRED> 

<!ELEMENT include (include|exclude)*>
<!ATTLIST include pattern CDATA #IMPLIED> 
<!ATTLIST include regex   CDATA #IMPLIED> 

<!ELEMENT exclude (include|exclude)*>
<!ATTLIST exclude pattern CDATA #IMPLIED> 
<!ATTLIST exclude regex   CDATA #IMPLIED> 

<!ELEMENT access-rule (deny,(allow|deny)*)>
<!ELEMENT allow (from?,to?,(allow|deny)*)>
<!ELEMENT deny  (from?,to?,(allow|deny)*)>
<!ELEMENT from  (message?,(include|exclude)*)>
<!ELEMENT to    (message?,(include|exclude)*)>
<!ATTLIST from pattern CDATA #IMPLIED> 
<!ATTLIST to   pattern CDATA #IMPLIED> 
<!ATTLIST from regex   CDATA #IMPLIED> 
<!ATTLIST to   regex   CDATA #IMPLIED> 
<!ELEMENT message (#PCDATA)>

=== pcantrell/macker/macker/test/macker-sample-big.xml
<?xml version="1.0"?>
<!DOCTYPE macker SYSTEM "file:///Users/paul/macker/src/macker.dtd">

<macker>
    
    <ruleset>
    
        <pattern name="any-component">
            <include regex="com.retek.**">
                <exclude regex="com.retek.core.**" />
                <exclude regex="com.retek.util.**" />
            </include>
        </pattern>

        <foreach var="the-component" regex="(${any-component}).impl.**">

            <!--== Patterns ==-->
        
            <!-- Component Layers -->
            
            <pattern name="data">
                <include regex="${the-component}.impl.data.**" />
            </pattern>
            <pattern name="logic">
                <include regex="${the-component}.impl.logic.**" />
            </pattern>
            <pattern name="remote">
                <include regex="${the-component}.impl.remote.**" />
            </pattern>
            <pattern name="api-impl">
                <include regex="${the-component}.impl.**">
                    <exclude pattern="data" />
                    <exclude pattern="logic" />
                    <exclude pattern="remote" />
                </include>
            </pattern>
            <pattern name="api">
                <include regex="${the-component}.**">
                    <exclude regex="${the-component}.impl.**" />
                </include>
            </pattern>

            <pattern name="entity-id">
                <include regex="${the-component}.*ID" />
            </pattern>
<!--            
            <pattern name="entity-id">
                <include pattern="api">
                    <filter type="extends">
                        <param name="super" value="com.retek.core.EntityID" />
                    </filter>
                </include>
            </pattern>
-->
        
            <!-- Other Objects -->
            
            <pattern name="other-component">
                <include pattern="any-component">
                    <exclude regex="${the-component}.**" />
                </include>
            </pattern>
            <pattern name="external">
                <exclude pattern="any-component" />
            </pattern>
            
            <!--== Rules ==-->
            
            <!-- To-centric -->
            
            <access-rule>
                <deny>
                    <to>
                        <message>Access to the component ${the-component} is limited.</message>
                        <include regex="${the-component}.**" />
                    </to>
                    
    <!--
                    <allow>
                        <from>
                            <message>Data objects may only refer to other layers and components through entity IDs.</message>
                            <include pattern="data"/>
                        </from>
                        <to><invlude pattern="entity-id"></to>
                    </allow>
    -->
                    <allow>
                        <from>
                            <include pattern="logic" />
                            <include pattern="remote" />
                        </from>
                        <to>
                            <message>Only a component's logic and remote access layers may reference its data layer.</message>
                            <include pattern="data" />
                        </to>
                    </allow>
                    <allow>
                        <from><include pattern="remote"/></from>
                        <to>
                            <message>Only a component's remote access layer may reference its logic layer.</message>
                            <include pattern="logic" />
                        </to>
                    </allow>
                    <allow>
                        <from><include pattern="api-impl"/></from>
                        <to>
                            <message>Only a component's client-side API implementation may reference its remote access layer.</message>
                            <include pattern="remote" />
                        </to>
                    </allow>
                    <allow>
                        <from>
                            <include pattern="api-impl" />
                            <include pattern="other-component" />
                        </from>
                        <to>
                            <message>A component's internal layers may not reference its external API.</message>
                            <include pattern="api" />
                        </to>
                    </allow>
                    <allow>
                        <from>
                            <include pattern="logic" />
                            <include pattern="other-component" />
                        </from>
                        <to>
                            <message>Only the logic layer of a component may reference other components.</message>
                            <include pattern="other-component" />
                        </to>
                    </allow>
                    <allow>
                        <to><include pattern="external"/></to>
                    </allow>
                </deny>
            </access-rule>
                
            <!-- From-centric -->

            <access-rule>
                <deny>
                    <to><include regex="${the-component}.**"/></to>
                    
                    <allow>
                        <from>
                            <message>A component's logic layer may reference only its data layer, and other components' APIs.</message>
                            <include regex="${logic}" />
                        </from>
                        <to>
                            <include regex="${data}" />
                            <include regex="${other-component}" />
                        </to>
                    </allow>
                    <allow>
                        <from>
                            <message>A component's remote access layer may reference only its logic and data layers.</message>
                            <include regex="${remote}" />
                        </from>
                        <to>
                            <include regex="${data}" />
                            <include regex="${logic}" />
                        </to>
                    </allow>
                    <allow>
                        <from>
                            <message>A component's client-side API implementation may reference only the API and the remote access layer.</message>
                            <include regex="${api-impl}" />
                        </from>
                        <to>
                            <include regex="${remote}" />
                            <include regex="${api}" />
                        </to>
                    </allow>
                    <allow>
                        <from>
                            <message>External classes must access a component through its API.</message>
                            <include regex="${external}" />
                        </from>
                        <to><include regex="${api}"/></to>
                    </allow>
                    <allow>
                        <from><include regex="**"/></from>
                        <to>  <include regex="${external}"/></to>
                    </allow>
                </deny>
            </access-rule>
            
        </foreach>
        
    </ruleset>    
        
</macker>

=== pcantrell/macker/macker/test/macker-sample.xml
<?xml version="1.0"?>
<!DOCTYPE macker SYSTEM "file:///Users/paul/macker/macker.dtd">

<macker>
    
    <ruleset name="Macker internal rules">
    
        <pattern name="macker">
            <include regex="net.innig.macker.**" />
        </pattern>
        
        <pattern name="structure">
            <include pattern="macker">
                <include regex="*.structure.**" />
            </include>
        </pattern>

        <pattern name="rule">
            <include pattern="macker">
                <include regex="*.rule.**" />
            </include>
        </pattern>
        
        <pattern name="event">
            <include pattern="macker">
                <include regex="*.rule.**" />
            </include>
        </pattern>
        
        <pattern name="main">
            <include pattern="macker">
                <exclude regex="net.innig.macker.*.**" />
            </include>
        </pattern>
        
        <pattern name="exception">
            <include regex="**Exception" />
        </pattern>
        
        <access-rule>
            <deny>
                <from>
                    <include pattern="structure" />
                </from>
                <to>
                    <include pattern="rule" />
                    <include pattern="event" />
                </to>
            </deny>
        </access-rule>

        <foreach var="foo" regex="(**Type)">
            <access-rule>
                <deny>
                    <from regex="${foo}" />
                    <to regex="**" />
                    
                    <allow><to regex="java.**" /></allow>
                    <allow><to regex="javax.**" /></allow>
                    <allow><to regex="net.innig.util.EnumeratedType" /></allow>
                </deny>
            </access-rule>
        </foreach>

    </ruleset>
        
</macker>
